### ISSUE TITLE
Resolution?

### ISSUE THREAD

**Issue by krulci** [nrkorte/McGraw-Bot#1]
When the bot ran into mistakes where it has to "Read about the concept", if the button is out of the screen, the bot hangs.
However, manually zoom out does work.
Also, as described in readme, drag and drop ording question is still an issue.

**Comment by krulci** [comment]
```
C:\Users\_\source\repos\McGraw-Bot\bot_admin.py:31: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  self.driver = webdriver.Chrome(executable_path=r"./chromedriver.exe")

DevTools listening on ws://127.0.0.1:51000/devtools/browser/1ad82d16-f94e-44dd-9a28-6f1ebcac6c60
[29792:33156:0220/213827.396:ERROR:device_event_log_impl.cc(218)] [21:38:27.396] USB: usb_device_win.cc:66 Failed to open \\?\usb#root_hub30#4&393adc3c&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}: Access is denied. (0x5)
1 Failed, 2 Failed, 3 Failed, 4 Failed.Traceback (most recent call last):
  File "C:\Users\_\source\repos\McGraw-Bot\bot_admin.py", line 473, in <module>
    bot.mcbegin()
  File "C:\Users\_\source\repos\McGraw-Bot\bot_admin.py", line 72, in mcbegin
    solve_matching_question(self, dictionary_for_answers, prompt_in_question)
  File "C:\Users\_\source\repos\McGraw-Bot\bot_admin.py", line 248, in solve_matching_question
    prompt_array = create_prompt_array_for_matching(self, number_of_answers)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\_\source\repos\McGraw-Bot\bot_admin.py", line 437, in create_prompt_array_for_matching
    prompt_array[2] = prompt_array[2].split("\n", 1)[0]
                      ~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by nrkorte** [comment]
Sorry for just seeing this, I don't have any classes that give me access to McGraw Hill Connect this semester, and can't debug any further.

For the "Read About the Concept" problem, my program selects that element by clicking on it which requires it to be on screen while it runs otherwise it will not be able to find it because the HTML elements are dynamically loaded based on screen size on the MHC site. This just means make sure your window is large enough that the button will be visible otherwise my program will halt.

For the index error, I'm not sure why I hardcoded the prompt_array values but I will merge a commit to fix that bug tonight. If you want you can re-download the new McTar.gz file or you can manually change lines 436-438 and replace them with this:

`    for i in range(0, len(prompt_array)):
        prompt_array[i] = prompt_array[i].split("\n", 1)[0]
`
