### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by krulci** [nrkorte/McGraw-Bot#3]
I think it will be a good idea of serializing the dictionary in to a json so that we can continue previous session if we ever encounter any issue.

**Comment by nrkorte** [comment]
Okay, I whipped up a quick beta for storing the information in a JSON file instead of a dictionary. Unfortunately, given how often this program crashes, I think the JSON needs to be rewritten every time we find a new question, this might make it slower or faster depending on how many times you plan to run the same program. I added the usage to the README at the bottom, let me know of any errors/bugs!

**Comment by krulci** [comment]
Might be good to also set the username, password, and link in a json file as this make it easier to use.
```py
if __name__ == "__main__":
# arguments in order : username, password, link to hw
    # print("Python version: ", sys.version)
    # if (len(sys.argv) != 4):
    #     raise Exception("Wrong number of program arguments: found ", len(sys.argv) ," needed 3 additional. Exiting now...")
    with open("credential.json", "r") as json_file:
        credential = json.load(json_file)
    bot = mcbot()
    bot.mcstart(credential["username"], credential["password"], credential["link"])
    bot.mcbegin()
```
